Beautiful metadata
ipfs-search/dweb-search-frontend pull request #193
Opened 2022-05-26 20:17 UTC by femans

This PR, which follows up on #192, the metadata is displayed much better. 

This is a stepping stone towards creating metadata-based filters and debugging filter behavior in general.

2022-05-28 15:04 UTC, dokterbob requested changes
This is really cool! Love to have this.

However, apart from some mentioned remarks, there is one issue which I think is a blocking one. Because of the large amount of data, the current view is a completely overwhelming one. Most users can't deal with such a large amount of fields (which is why Kees originally left them off). 

What I would imagine is either creating another drop-open menu with extra metadata analogous to the 'Show file info' one *or* creating a nested drop-open thing so the extra metadata expands from the 'Show file info'. 

![image](https://user-images.githubusercontent.com/22742/170830970-a9001632-fb17-46e1-acbd-f17c71ebba44.png)

2022-05-30 11:40 UTC, femans commented on src/components/results/detail/helpers/MetaDataPanel.vue
>        // TODO: See if all fields are there.
Am I missing something? I removed the todo because I fixed it in the following lines.

2022-05-30 16:33 UTC, dokterbob commented on src/components/results/detail/helpers/MetaDataPanel.vue
> +      return extraData.concat(Object.entries(this.file.metadata?.metadata)
I agree that it is a bit tricky to harmonise search results and metadata, although the transformation is clearly defined here: https://github.com/ipfs-search/ipfs-search-api/blob/master/server/search/transform_results.js

I do think we should harmonise this, potentially even transform the actual data in our index but this is a very sticky subject as it touches so many components of our architecture.

For now, perhaps we can live with this duplicity for now. I would suggest that on the long term our strategy should be to harmonise the data on the frontend now, so we can use metadata to fill in title and mimetype, perhaps factoring out `transform_results`.

2022-05-30 18:01 UTC, femans commented on src/components/results/detail/helpers/MetaDataPanel.vue
>        // TODO: See if all fields are there.
ok the problem is with that that I made a preselection which fields are displayed, and I don't know if there could be other fields coming back from the API or how to find out.

2022-05-30 19:20 UTC, dokterbob commented on src/components/results/detail/helpers/MetaDataPanel.vue
>        // TODO: See if all fields are there.
I would suggest you either implement the TODO (testing for presence of `key` in `this.file` should do, if I understand this right) or add your above explanation, but adding to it which fields (e.g. metadata or search-API fields) and which API (metadata or search).

2022-05-30 20:12 UTC, femans commented on src/components/results/detail/helpers/MetaDataPanel.vue
>        // TODO: See if all fields are there.
actually, this was an obsolete method, my bad. Removed now.

2022-05-30 20:31 UTC, femans commented
> This is really cool! Love to have this.
> 
> However, apart from some mentioned remarks, there is one issue which I think is a blocking one. Because of the large amount of data, the current view is a completely overwhelming one. Most users can't deal with such a large amount of fields (which is why Kees originally left them off).

N.b. They weren't previously there.

> 
> What I would imagine is either creating another drop-open menu with extra metadata analogous to the 'Show file info' one _or_ creating a nested drop-open thing so the extra metadata expands from the 'Show file info'.

Ok, created the nested dropdown, good idea.

2022-06-01 11:59 UTC, merged