updated shutdown text
ipfs-search/dweb-search-frontend pull request #299
Opened 2023-05-30 16:06 UTC by femans

2023-05-30 16:25 UTC, dokterbob requested changes

2023-05-30 16:25 UTC, dokterbob commented on src/components/HomeView.vue
> +            <b>we will to shut down our public APIs June the 7th, 2023</b>, we don't know for how
will have to shut down

2023-05-30 16:44 UTC, femans commented on src/components/HomeView.vue
> +            <b>we will to shut down our public APIs June the 7th, 2023</b>, we don't know for how
will shut down

2023-05-30 20:44 UTC, dokterbob approved these changes

2023-05-30 20:44 UTC, dokterbob commented on src/components/HomeView.vue
> +            <b>we will shut down our public APIs June the 7th, 2023</b>, we don't know for how long.
I would suggest the word suspend, skipping the 'we don't know for how long'. But not essential.

Otherwise o.k.

2023-05-31 09:09 UTC, femans commented on src/components/HomeView.vue
> +            <b>we will shut down our public APIs June the 7th, 2023</b>, we don't know for how long.
signal that we may come back, depending on evolving circumstances. Otherwise it seems definitive.

2023-05-31 09:10 UTC, merged